export const FIREBASE_EVENTS = {
  EVENT_CREATE:'CREATE_INTERNAL_REQUEST',
  EVENT_RECEIVE:'RECEIVE_INTERNAL_REQUEST',
  EVENT_FULFILL:'FULFILL_INTERNAL_REQUEST',
  EVENT_REJECT:'REJECT_INTERNAL_REQUEST',
  EVENT_RELEASE:'RELEASE_INTERNAL_REQUEST',
  EVENT_TIMEOUT:'TIMEOUT_INTERNAL_REQUEST',
  EVENT_CONFIRM:'CONFIRM_INTERNAL_REQUEST',
  EVENT_UPDATE_PRIORITY:'UPDATE_PRIORITY_INTERNAL_REQUEST',
  EVENT_REPORT_MISSING_BOX:'REPORT_MISSING_BOX',
}